Repository acm-ucr/art-factory-website, pull requests merged in 2024-05, with the labels that each got.

#91 Adjust gallerycards
  src/app/about/page.js
  src/components/gallery/GalleryCards.jsx
Labels: Ready for Review, responsiveness

#93 changed what.jsx
  src/components/home/What.jsx
Labels: Ready for Review

#97 fix project cards
  src/components/home/ProjectType.jsx
  src/components/home/ProjectTypes.jsx
Labels: Ready for Review

#101 Fixed responsiveness for Landing page
  src/components/about/AboutLanding.jsx
Labels: Ready for Review, Landing, responsiveness

#104 Animated Board
  package-lock.json
  package.json
  src/components/board/Board.jsx
  src/components/board/Boards.jsx
Labels: enhancement, Ready for Review

#99 fixed responsiveness of Socials
  src/components/home/Socials.jsx
Labels: do not merge

#106 fixed upon the previous requests
  src/components/home/Socials.jsx
  src/data/socials.js
Labels: duplicate, Ready for Review, responsiveness

#94 Lillian/clean config
  src/components/Button.jsx
  src/components/Error.jsx
  src/components/Navigation.jsx
  src/components/board/Board.jsx
  src/components/gallery/GalleryHeader.jsx
  src/components/home/ProjectTypes.jsx
  tailwind.config.js
Labels: Ready for Review

#86 Calendar
  package-lock.json
  package.json
  src/app/events/page.js
  src/components/Calendar/Calendar.jsx
  src/components/Calendar/CustomEvents.jsx
  src/components/Calendar/CustomHeader.jsx
  src/components/Calendar/CustomToolbar.jsx
  src/components/Calendar/Modal.jsx
  src/components/Calendar/index.css
  tailwind.config.js
Labels: Ready for Review, Events

#110 nav bar
  src/app/layout.js
  src/app/page.js
  src/components/Navigation.jsx
  src/components/NavigationBS.jsx
  src/data/navigation.js
  tailwind.config.js
Labels: Ready for Review, responsiveness

#116 fixed board colors
  src/components/board/Board.jsx
Labels: Ready for Review

#115 animated about
  src/components/about/AboutLanding.jsx
Labels: Ready for Review

#114 Stanley/animatelandingbg
  src/components/home/Landing.jsx
Labels: Ready for Review

#98 Project cards animations
  src/components/home/ProjectType.jsx
  src/components/home/ProjectTypes.jsx
Labels: Ready for Review

#95 made gallery landing
  package-lock.json
  public/left.svg
  src/components/about/About.jsx
  src/components/gallery/GalleryLanding.jsx
Labels: Ready for Review
