Repository acm-ucr/art-factory-website, pull requests merged in 2024-06, with the labels that each got.

#123 animation add in About
  src/components/about/About.jsx
Labels: enhancement, About

#121 fixed response on gallery logo
  package-lock.json
  src/components/gallery/GalleryLanding.jsx
Labels: Ready for Review, responsiveness

#118 meowmeowmeow
  src/components/home/What.jsx
Labels: Ready for Review

#122 Fixed nav bar
  src/components/Navigation.jsx
Labels: Ready for Review, responsiveness

#108 fix project card and gallery
  src/app/gallery/page.js
  src/components/Navigation.jsx
  src/components/NavigationBS.jsx
  src/components/gallery/GalleryCards.jsx
  src/components/gallery/GalleryLanding.jsx
  src/components/home/ProjectType.jsx
  src/components/home/Socials.jsx
  src/data/images.js
  src/data/socials.js
Labels: Ready for Review
