Repository acm-ucr/art-factory-website, pull requests merged in 2024-04, with the labels that each got.

#15 botton
  public/leftring.svg
  public/rightring.svg
  src/app/page.js
  src/components/Button.jsx
Labels: Ready for Review

#24 "Get Involved" done in landing
  src/app/page.js
  src/components/Link.jsx
  src/components/Links.jsx
  src/components/Socials.jsx
  src/data/socials.js
Labels: Ready for Review, needs address, Landing, do not merge

#27 Title Component
  src/app/page.js
  src/components/Socials.jsx
  src/components/Title.jsx
Labels: Ready for Review

#29 Projects Component
  public/Logo.svg
  public/cards/Vector.svg
  public/cards/hand.svg
  public/cards/origami.svg
  public/cards/paintbrush.svg
  public/cards/pencil.svg
  src/app/page.js
  src/components/ProjectType.jsx
  src/components/ProjectTypes.jsx
  tailwind.config.js
Labels: help wanted, Ready for Review

#14 stanley/landing
  public/BRCloud.svg
  public/TLCloud.svg
  public/TRCloud.svg
  public/clouds/BigCloud.svg
  public/clouds/BiggerCloud.svg
  public/clouds/NormalCloud.svg
  public/clouds/PinkCloud.svg
  public/clouds/SmallCloud.svg
  public/landingbg.svg
  public/landingtitle.svg
  src/components/Landing.jsx
Labels: Ready for Review, Landing, responsiveness

#39 social fix
  src/components/Socials.jsx
Labels: Ready for Review

#41 new colors, error page, button
  public/errorclouds.svg
  public/oopseasel.svg
  src/app/error.js
  src/app/layout.js
  src/app/not-found.js
  src/components/Button.jsx
  src/components/Error.jsx
  tailwind.config.js
Labels: Ready for Review

#43 Board Cards
  src/app/board/page.js
  src/components/Cards.jsx
Labels: Ready for Review

#42 Implementing gallery cards
  src/app/gallery/page.js
  src/components/GalleryCards.jsx
  src/data/images.js
Labels: Ready for Review

#52 Nav Bar
  package-lock.json
  package.json
  public/icon.svg
  public/icon.webp
  src/components/Navigation.jsx
  src/data/navigation.js
Labels: Ready for Review

#55 Stanley/cards
  public/jonathan2024.webp
  src/app/board/page.js
  src/components/Button.jsx
  src/components/Title.jsx
  src/components/board/Card.jsx
  src/components/board/Cards.jsx
  src/components/home/Landing.jsx
  src/data/board.js
  tailwind.config.js
Labels: Ready for Review

#56 fix mobile device width
  src/components/about/About.jsx
Labels: Ready for Review

#60 Vraj/icons
  public/logo.svg
  src/components/home/Socials.jsx
  src/data/socials.js
Labels: Ready for Review

#59 Gallerycards mobile responsiveness
  src/components/gallery/GalleryCards.jsx
Labels: Ready for Review, responsiveness

#28 about us landing page
  public/LogoLanding.svg
  src/app/about/page.js
  src/components/about/AboutLanding.jsx
Labels: Ready for Review, Landing, About

#44 added title component to about section
  src/app/page.js
  src/components/home/AboutSection.jsx
Labels: Ready for Review

#66 Liamregina/footer component
  public/paint.svg
  src/components/Footer.jsx
  tailwind.config.js
Labels: Ready for Review

#65 Responsive Cards
  src/components/home/ProjectTypes.jsx
Labels: Ready for Review

#61 Lillian/board
  src/app/board/page.js
  src/data/board.js
Labels: Ready for Review

#81 implmented framer dependecies
  package-lock.json
  package.json
  src/app/board/page.js
  src/app/page.js
  src/components/board/Board.jsx
  src/components/board/Boards.jsx
  src/components/home/What.jsx
Labels: Ready for Review

#90 Gallery Continous
  src/components/gallery/GalleryCards.jsx
Labels: Ready for Review

#89 Add project card button and description
  src/components/home/ProjectType.jsx
  src/components/home/ProjectTypes.jsx
Labels: Ready for Review
